#!/usr/bin/perl

BEGIN { $ENV{DBIC_TRACE} = 0 };

use strict;
use warnings;
use feature qw( :5.10 );

my $name = shift;

unless(defined $name)
{
  say "usage: nx_nebraska_import name";
  exit 1;
}

my $mod = "NX::Nebraska::Import::Source::$name";

eval "use $mod";
if(my $error = $@)
{
  print STDERR "bad source: $name\n";
  die $error;
  exit 1;
}

my $source = $mod->new;

say "fetch";
$source->fetch_data;
say "import";
$source->import_data;
