#!/usr/bin/perl

use strict;
use warnings;
use feature qw( :5.10 );
use NX::Nebraska::Schema;

my $db = shift // 'data';
my $dsn = shift // "dbi:SQLite:dbname=/var/lib/nebraska/$db.sqlite";
my $user = shift // '';
my $pass = shift // '';

if($db eq 'data')
{
  my $schema = NX::Nebraska::Schema->connect($dsn, $user, $pass);
  $schema->deploy;
}

else
{
  say "no information on db=$db";
  exit;
}