#!/usr/bin/perl

BEGIN { $ENV{DBIC_TRACE} = 0 }

use strict;
use warnings;
use feature qw( :5.10 );
use NX::Nebraska;

foreach my $auser (NX::Nebraska->model('User::UserAnon')->search({ free => 0 })->all)
{
  my $age_in_hours = (time - $auser->modified_at->epoch) / (60*60);
  next unless $age_in_hours > 8;
  NX::Nebraska->model('User::TripVisit')->search({ user_id => $auser->user_id })->delete;
  $auser->free(1);
  $auser->update;
}
