#!/usr/bin/perl

BEGIN { $ENV{DBIC_TRACE} = 0 }

use strict;
use warnings;
use feature qw( :5.10 );
use NX::Nebraska;
use YAML ();
use utf8;

my %has_flag = (
  au => 1,
  us => 1,
  ru => 0,
  eu2 => 0,
  xa1 => 0,
);

my %is_small = (
  eu2 => {
    map { $_ => 1 } qw( va li je im ad sm mc lu gg mt ),
  },
  xa1 => {
    map { $_ => 1 } qw( gw gq bi dj rw tg sz gm cv km mu sc yt sh re st ),
  },
  us => {
    map { $_ => 1 } qw( DC ),
  },
  ru => {
    map { $_ => 1 } qw ( KB AD IN SE MOW SPE ),
  },
);

my %override_name = (
  xa1 => {
    re => 'Réunion',
    #re => 'Reunion',
    st => 'São Tomé and Príncipe',
    #st => 'Sao Tome and Principe',
  },
);

utf8::decode($override_name{xa1}->{re});
utf8::decode($override_name{xa1}->{st});

NX::Nebraska->model('DB::Factoid')->delete;

foreach my $map_id (qw( eu2 xa1 ))
{
  my $fn = NX::Nebraska->config->{root} . "/svg/$map_id.svg";
  open(IN, $fn) || die "unable to read $fn $!";
  while(<IN>)
  {
    if(/id="([a-z][a-z])"/)
    {
      my $country_code = $1;
      my $place = NX::Nebraska->model('DB::Place')->search({ map_code => $country_code,  map_id => ['eu1','xa1'] })->first;
      die "could not find place for $country_code" unless defined $place;
      my $trip_place = NX::Nebraska->model('DB::TripPlace')->search({
        country_code => $country_code,
        region_code => undef,
      })->first;
      my $name = $override_name{$map_id}->{$country_code} // $place->name;
      if(defined $trip_place)
      {
        $trip_place->flag($has_flag{$map_id});
        $trip_place->name($name);
        $trip_place->update;
      }
      else
      {
        $trip_place = NX::Nebraska->model('DB::TripPlace')->create({
          country_code => $country_code,
          region_code => undef,
          flag => $has_flag{$map_id},
          name => $name,
        });
      }
      
      # CREATE or UPDATE trip_place_map
      my $trip_place_map = NX::Nebraska->model('DB::TripPlaceMap')->search({
        trip_place_id => $trip_place->id,
        map_id => $map_id,
      })->first;
      if(defined $trip_place_map)
      {
        $trip_place_map->map_code($country_code);
        $trip_place_map->small($is_small{$map_id}->{$country_code} // 0);
        $trip_place_map->update;
      }
      else
      {
        $trip_place_map = NX::Nebraska->model('DB::TripPlaceMap')->create({
          trip_place_id => $trip_place->id,
          map_id => $map_id,
          map_code => $country_code,
          small => $is_small{$map_id}->{$country_code} // 0,
        });
      }
      
      # find any factoids from the statistics
      if(my $people_stat = $place->most_interesting_statistic('people'))
      {
        given($people_stat->name)
        {
          when('population (est)') { add_factoid($trip_place, "Population estimate in " . $people_stat->year . " was " . human_readable_number($people_stat->value)) }
          when('population (census)') { add_factoid($trip_place, "Census recorded " . human_readable_number($people_stat->value) . " people in " . $people_stat->year) }
          default { die "unknown name", $people_stat->name }
        }
      }
    
      if(my $area_stat = $place->most_interesting_statistic('km%'))
      {
        if($area_stat->name eq 'area (km²)')
        {
          add_factoid($trip_place, "Area is " . human_readable_number($area_stat->value) . " km²");
        }
        else
        {
          die "unknown name", $area_stat->name;
        }
      }
      
    }
  }
  close IN;
}

foreach my $country_code (qw( au us ru ca mx ))
{
  my $map_id = $country_code . "1";
  foreach my $place (NX::Nebraska->model('DB::Place')->search({ map_id => $map_id})->all)
  {
  
    # CREATE or UPDATE trip_place
    my $trip_place = NX::Nebraska->model('DB::TripPlace')->search({
      country_code => $country_code,
      region_code => $place->map_code,
    })->first;
    if(defined $trip_place)
    {
      $trip_place->flag($has_flag{$country_code});
      $trip_place->name($place->name);
      $trip_place->update;
    }
    else
    {
      $trip_place = NX::Nebraska->model('DB::TripPlace')->create({
        country_code => $country_code,
        region_code => $place->map_code,
        flag => $has_flag{$country_code},
        name => $place->name,
      });
    }
    
    # CREATE or UPDATE trip_place_map
    my $trip_place_map = NX::Nebraska->model('DB::TripPlaceMap')->search({
      trip_place_id => $trip_place->id,
      map_id => $map_id,
    })->first;
    if(defined $trip_place_map)
    {
      $trip_place_map->map_code($place->map_code);
      $trip_place_map->small($is_small{$country_code}->{$place->map_code} // 0);
      $trip_place_map->update;
    }
    else
    {
      $trip_place_map = NX::Nebraska->model('DB::TripPlaceMap')->create({
        trip_place_id => $trip_place->id,
        map_id => $map_id,
        map_code => $place->map_code,
        small => $is_small{$country_code}->{$place->map_code} // 0,
      });
    }
    
    my $place_code = "$country_code-".$place->map_code;
    if(my $f = data()->{$place_code})
    {
      while(my($fact,$data) = each %$f)
      {
        my $txt;
        given($fact)
        {
          when(/^(state |)(crustacean|game bird|bird|dinosaur|butterfly|state insect|amphibian|state waterfowl|wild game bird)$/)
          { $txt = "The official $fact is the [" . $data->{name} .']' }
          when('state beverage')
          { $txt = "The official $fact is [" . $data->{name} . ']' }
          default
          { die "unknown fact type: $fact" }
        }
        add_factoid($trip_place, $txt, $data->{url});
      }
    }
    
    # find any factoids from the statistics
    if(my $people_stat = $place->most_interesting_statistic('people'))
    {
      given($people_stat->name)
      {
        when('population (est)') { add_factoid($trip_place, "Population estimate in " . $people_stat->year . " was " . human_readable_number($people_stat->value)) }
        when('population (census)') { add_factoid($trip_place, "Census recorded " . human_readable_number($people_stat->value) . " people in " . $people_stat->year) }
        default { die "unknown name", $people_stat->name }
      }
    }
    
    if(my $area_stat = $place->most_interesting_statistic('km%'))
    {
      if($area_stat->name eq 'area (km²)')
      {
        add_factoid($trip_place, "Area is " . human_readable_number($area_stat->value) . " km²");
      }
      else
      {
        die "unknown name", $area_stat->name;
      }
    }
  }
}

sub add_factoid
{
  my $trip_place = shift;
  my $fact = shift;
  my $url = shift;
  utf8::decode($fact);
  NX::Nebraska->model('DB::Factoid')->create({
    trip_place_id => $trip_place->id,
    factoid => $fact,
    url => $url,
  });
}

sub human_readable_number
{
  my $in = join "", reverse split //, shift;
  my $out = '';
  while($in =~ s/^(\d\d\d)(\d)/$2/)
  {
    $out .= $1 . ",";
  }
  $out .= $in;
  return join "", reverse split //, $out;
}

sub data
{
  state $data;
  return $data if defined $data;
  
  $data = {};
  my $place_code;
  binmode DATA, ':utf8';
  while(<DATA>)
  {
    chomp;
    s/#.*$//;
    next if $_ eq '';
    if(/^\[(.*)\]$/)
    {
      $place_code = $1;
      die "$place_code shows up twice!" if exists $data->{$place_code};
      $data->{$place_code} = {};
      next;
    }
    
    my($fact, $name, $url) = split /\|/;
    $data->{$place_code}->{$fact} = {
      name => $name,
      url => $url,
    };
  }
  
  return $data;
}

__DATA__
[us-AB]
state bird|Yellowhammer|http://en.wikipedia.org/wiki/Northern_Flicker
state game bird|Wild Turkey|http://en.wikipedia.org/wiki/Wild_Turkey
state spirit|Conecuh Ridge Whiskey|http://en.wikipedia.org/wiki/Conecuh_Ridge_Whiskey
state amphibian|Red Hills salamander|http://en.wikipedia.org/wiki/Red_Hills_salamander
state insect|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-AK]
state bird|Puffin|http://en.wikipedia.org/wiki/Puffin
state beverage|Milk
state butterfly|Diana Fritillary Butterfly|http://en.wikipedia.org/wiki/Diana_Fritillary
[us-AZ]
state bird|Cactus Wren|http://en.wikipedia.org/wiki/Cactus_Wren
state amphibian|Arizona Tree Frog|http://en.wikipedia.org/wiki/Hyla_eximia
state butterfly|Two-tailed Swallowtail|http://en.wikipedia.org/wiki/Two-tailed_Swallowtail
[us-AR]
state bird|Mockingbird|http://en.wikipedia.org/wiki/Northern_Mockingbird
[us-CA]
state bird|California Quail|http://en.wikipedia.org/wiki/California_Quail
state beverage|Wine
state butterfly|California Dogface Butterfly|http://en.wikipedia.org/wiki/California_dogface_butterfly
[us-CO]
state bird|Lark Bunting|http://en.wikipedia.org/wiki/Lark_Bunting
state butterfly|Colorado Hairstreak Butterfly|http://en.wikipedia.org/wiki/Colorado_Hairstreak_Butterfly
state dinosaur|Stegosaurus|http://en.wikipedia.org/wiki/Stegosaurus
[us-CT]
state bird|American Robin|http://en.wikipedia.org/wiki/American_Robin
[us-DE]
state bird|Blue Hen Chicken|http://en.wikipedia.org/wiki/Blue_Hen_of_Delaware
state beverage|Milk
state butterfly|Eastern Tiger Swallowtail|http://en.wikipedia.org/wiki/Eastern_tiger_swallowtail
[us-DC]
bird|Wood Thrush|http://en.wikipedia.org/wiki/Wood_Thrush
dinosaur|Capitalsaurus|http://en.wikipedia.org/wiki/Capitalsaurus
[us-FL]
state bird|Northern Mockingbird|http://en.wikipedia.org/wiki/Northern_Mockingbird
state beverage|Orange Juice
state butterfly|Zebra Longwing|http://en.wikipedia.org/wiki/Heliconius_charithonia
[us-GA]
state bird|Brown Thrasher|http://en.wikipedia.org/wiki/Brown_Thrasher
state game bird|Bobwhite Quail|http://en.wikipedia.org/wiki/Bobwhite_Quail
state amphibian|American Green Tree Frog|http://en.wikipedia.org/wiki/American_Green_Tree_Frog
state butterfly|Eastern Tiger Swallowtail|http://en.wikipedia.org/wiki/Eastern_tiger_swallowtail
[us-HI]
#state bird|Nēnē|http://en.wikipedia.org/wiki/Hawaiian_Goose
state bird|Hawaiian Goose|http://en.wikipedia.org/wiki/Hawaiian_Goose
state insect|Kamehameha Butterfly|http://en.wikipedia.org/wiki/Kamehameha_butterfly
[us-ID]
state bird|Mountain Bluebird|http://en.wikipedia.org/wiki/Mountain_Bluebird
state insect|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-IL]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state amphibian|Eastern Tiger Salamander|http://en.wikipedia.org/wiki/Tiger_Salamander
state insect|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-IN]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state beverage|Water
[us-IA]
state bird|Eastern Goldfinch|http://en.wikipedia.org/wiki/Eastern_Goldfinch
state amphibian|North American Bullfrog|http://en.wikipedia.org/wiki/Bullfrog
[us-KS]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state amphibian|Barred Tiger Salamander|http://en.wikipedia.org/wiki/Ambystoma_mavortium
[us-KY]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state beverage|Milk
state butterfly|Viceroy Buttefly|http://en.wikipedia.org/wiki/Viceroy_butterfly
[us-LA]
state bird|Brown Pelican|http://en.wikipedia.org/wiki/Brown_Pelican
state beverage|Milk
state amphibian|American Green Tree Frog|http://en.wikipedia.org/wiki/American_Green_Tree_Frog
state crustacean|Louisiana Crawfish|http://en.wikipedia.org/wiki/Procambarus_clarkii
[us-ME]
state bird|Black-capped Chicadee|http://en.wikipedia.org/wiki/Black-capped_Chickadee
state beverage|Moxie
[us-MD]
state bird|Baltimore Oriole|http://en.wikipedia.org/wiki/Baltimore_Oriole
state beverage|Milk
state butterfly|Baltimore Checkerspot Butterfly|http://en.wikipedia.org/wiki/Baltimore_Checkerspot
state crustacean|Maryland blue crab|http://en.wikipedia.org/wiki/Blue_crab
state dinosaur|Astrodon johnstoni|http://en.wikipedia.org/wiki/Astrodon_johnstoni
[us-MA]
state bird|Black-capped Chicadee|http://en.wikipedia.org/wiki/Black-capped_Chickadee
state game bird|Wild Turkey|http://en.wikipedia.org/wiki/Wild_Turkey
state beverage|Cranberry Juice
[us-MI]
state bird|American Robin|http://en.wikipedia.org/wiki/American_Robin
state beverage|Milk
[us-MN]
state bird|Common Loon|http://en.wikipedia.org/wiki/Common_Loon
state amphibian|Northern Leopard Frog|http://en.wikipedia.org/wiki/Northern_Leopard_Frog
state insect|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-MS]
state bird|Northern Mockingbird|http://en.wikipedia.org/wiki/Northern_Mockingbird
state waterfowl|Wood Duck|http://en.wikipedia.org/wiki/Wood_Duck
state butterfly|Spicebush Swallowtail|http://en.wikipedia.org/wiki/Spicebush_Swallowtail
[us-MO]
state bird|Eastern Bluebird|http://en.wikipedia.org/wiki/Eastern_Bluebird
state amphibian|North American Bullfrog|http://en.wikipedia.org/wiki/Bullfrog
state dinosaur|Hypsibema missouriensis|http://en.wikipedia.org/wiki/Hypsibema
[us-MT]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state butterfly|Mourning Cloak Butterfly|http://en.wikipedia.org/wiki/Mourning_cloak
[us-NE]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state beverage|Kool-Aid
[us-NV]
state bird|Mountain Bluebird|http://en.wikipedia.org/wiki/Mountain_Bluebird
[us-NH]
state bird|Purple Finch|http://en.wikipedia.org/wiki/Purple_Finch
state beverage|Apple Cider
state amphibian|Red-spotted Newt|http://en.wikipedia.org/wiki/Red-spotted_Newt
state butterfly|Karner Blue Butterfly|http://en.wikipedia.org/wiki/Karner_Blue
[us-NJ]
state bird|Eastern Goldfinch|http://en.wikipedia.org/wiki/Eastern_Goldfinch
state dinosaur|Hadrosaurus foulkii|http://en.wikipedia.org/wiki/Hadrosaurus
[us-NM]
state bird|Roadrunner|http://en.wikipedia.org/wiki/Greater_Roadrunner
state amphibian|New Mexico Spadefoot Toad|http://en.wikipedia.org/wiki/New_Mexico_Spadefoot_Toad
state butterfly|Sandia Hairstreak Butterfly|http://en.wikipedia.org/wiki/Sandia_Hairstreak
[us-NY]
state bird|Eastern Bluebird|http://en.wikipedia.org/wiki/Eastern_Bluebird
state beverage|Milk
state amphibian|Wood Frog|http://en.wikipedia.org/wiki/Wood_Frog
state butterfly|Red Spotted Purple Butterfly|http://en.wikipedia.org/wiki/Limenitis_arthemis
[us-NC]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state beverage|Milk
state butterfly|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-ND]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state beverage|Milk
[us-OH]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state beverage|Tomato Juice
[us-OK]
state bird|Scissor-tailed Flycatcher|http://en.wikipedia.org/wiki/Scissor-tailed_Flycatcher
state beverage|Milk
state amphibian|North American Bullfrog|http://en.wikipedia.org/wiki/Bullfrog
state butterfly|Black Swallowtail|http://en.wikipedia.org/wiki/Black_Swallowtail
[us-OR]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state beverage|Milk
state insect|Oregon Swallowtail|http://en.wikipedia.org/wiki/Oregon_Swallowtail
state crustacean|Dungeness Crab|http://en.wikipedia.org/wiki/Dungeness_crab
[us-PA]
state bird|Ruffed Grouse|http://en.wikipedia.org/wiki/Ruffed_Grouse
[us-RI]
state bird|Rhode Island Red Chicken|http://en.wikipedia.org/wiki/Rhode_Island_Red_Chicken
state beverage|Coffee Milk|http://en.wikipedia.org/wiki/Coffee_milk
[us-SC]
state bird|Carolina Wren|http://en.wikipedia.org/wiki/Carolina_Wren
state wild game bird|Wild Turkey|http://en.wikipedia.org/wiki/Wild_Turkey
state beverage|Milk
state amphibian|Spotted Salamander|http://en.wikipedia.org/wiki/Spotted_Salamander
state butterfly|Eastern Tiger Swallowtail|http://en.wikipedia.org/wiki/Eastern_tiger_swallowtail
[us-SD]
state bird|Common Pheasant|http://en.wikipedia.org/wiki/Common_Pheasant
state beverage|Milk
[us-TN]
state bird|Mockingbird|http://en.wikipedia.org/wiki/Northern_Mockingbird
state wild game bird|Bobwhite Quail|http://en.wikipedia.org/wiki/Bobwhite_Quail
state amphibian|Tennessee Cave Salamander|http://en.wikipedia.org/wiki/Tennessee_Cave_Salamander
state butterfly|Zebra Swallowtail|http://en.wikipedia.org/wiki/Zebra_Swallowtail
[us-TX]
state bird|Mockingbird|http://en.wikipedia.org/wiki/Northern_Mockingbird
state amphibian|Texas Toad|http://en.wikipedia.org/wiki/Texas_Toad
state insect|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
state dinosaur|Pleurocoelus|http://en.wikipedia.org/wiki/Pleurocoelus
[us-UT]
state bird|California Gull|http://en.wikipedia.org/wiki/California_Gull
[us-VT]
state bird|Hermit Thrush|http://en.wikipedia.org/wiki/Hermit_Thrush
state beverage|Milk
state amphibian|Northern Leopard Frog|http://en.wikipedia.org/wiki/Northern_Leopard_Frog
state butterfly|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-VA]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state beverage|Milk
state butterfly|Eastern Tiger Swallowtail|http://en.wikipedia.org/wiki/Eastern_tiger_swallowtail
[us-WA]
state bird|Willow Goldfinch|http://en.wikipedia.org/wiki/American_Goldfinch
state amphibian|Pacific Chorus Frog|http://en.wikipedia.org/wiki/Pacific_Chorus_Frog
[us-WV]
state bird|Northern Cardinal|http://en.wikipedia.org/wiki/Northern_Cardinal
state butterfly|Monarch Butterfly|http://en.wikipedia.org/wiki/Monarch_(butterfly)
[us-WI]
state bird|American Robin|http://en.wikipedia.org/wiki/American_Robin
state beverage|Milk
[us-WY]
state bird|Western Meadowlark|http://en.wikipedia.org/wiki/Western_Meadowlark
state dinosaur|Triceratops|http://en.wikipedia.org/wiki/Triceratops
